name: notification_wrapper
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/Nathaniel-Akubuo/notification_wrapper
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  jpush_flutter:
    git:
      url: https://github.com/jpush/jpush-flutter-plugin
      ref: dev-3.x

  # fcm
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

  # util
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
